# Generated by Django 5.2.1 on 2025-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Code & Coffee', max_length=255),
        ),
    ]
